.\" Man page for dasm8080
.\" Contact depositmail@rambler.ru
.TH Dasm8080 "07 Nov 2021"
.SH NAME
Dasm8080 \- Disassembler for i8080
.SH SYNOPSIS
Dasm8080 is a i8080 disassembler based on Qt and C++.
.SH DESCRIPTION
 Dasm8080 it is a GUI tool for disassembling executable
 files for the intel 8080 microprocessor. Licence: GNU GPL v.3.
.SH OPTIONS
No options for this man page
.SH SEE ALSO
man(1), groff(1), man.config(5)
.SH BUGS
If you find a bug, please report it at below address.
.SH AUTHOR
Oleg Kozhukharenko (depositmail@rambler.ru)
